version: "3"

services:

  ipfs_host:
    container_name: ipfs_host
    image: docker.io/ipfs/go-ipfs:latest
    restart: always
    volumes:
      - ./staging:/export
      - ./data:/data/ipfs
      - ./swarm.key:/home/.ipfs/swarm.key
    ports:
      - 4001:4001
      - 127.0.0.1:8080:8080
      - 127.0.0.1:5001:5001
